# dependency review doesn't support multiple-licensed packages (e.g Ruby)
# https://github.com/actions/dependency-review-action/issues/263
# https://github.com/cncf/foundation/blob/main/allowed-third-party-license-policy.md
allow-licenses:
- 'Apache-2.0'
- 'BSD-2-Clause'
- 'BSD-2-Clause-FreeBSD'
- 'BSD-3-Clause'
- 'ISC'
- 'MIT'
- 'PostgreSQL'
- 'Python-2.0'
- 'Ruby'
- 'X11'
- 'Zlib'

allow-dependencies-licenses:
# The following packages are available under multiple licenses, or aren't detected by the dependency review action
# https://github.com/actions/dependency-review-action/issues/263
# 'MIT'
- pkg:gem/mime-types-data
- pkg:gem/multi_json
- pkg:gem/rake
- pkg:gem/fluent-plugin-record-modifier
# 'MPL-2.0'
- pkg:gem/llhttp-ffi
# 'Ruby'
- pkg:gem/base64
