# https://github.com/cncf/foundation/blob/main/allowed-third-party-license-policy.md
allow-licenses:
- 'Apache-2.0'
- 'BSD-2-Clause'
- 'BSD-2-Clause-FreeBSD'
- 'BSD-3-Clause'
- 'ISC'
- 'MIT'
- 'PostgreSQL'
- 'Python-2.0'
- 'Ruby'
- 'X11'
- 'Zlib'

allow-dependencies-licenses:
# ostruct is available as open source under the terms of the 2-Clause BSD License.
# https://github.com/ruby/ostruct?tab=License-1-ov-file
- pkg:gem/ostruct
# csv is available as open source under the terms of the 2-Clause BSD License.
# https://github.com/ruby/csv?tab=BSD-2-Clause-1-ov-file#readme
- pkg:gem/csv
