# https://github.com/cncf/foundation/blob/main/allowed-third-party-license-policy.md
allow-licenses:
- 'Apache-2.0'
- 'BSD-2-Clause'
- 'BSD-2-Clause-FreeBSD'
- 'BSD-3-Clause'
- 'ISC'
- 'MIT'
- 'PostgreSQL'
- 'Python-2.0'
- 'Ruby'
- 'X11'
- 'Zlib'

allow-dependencies-licenses:
# dependency review doesn't support multiple-licensed packages 
# https://github.com/actions/dependency-review-action/issues/263
