# dependency review doesn't support multiple-licensed packages (e.g Ruby)
# https://github.com/actions/dependency-review-action/issues/263
# https://github.com/cncf/foundation/blob/main/allowed-third-party-license-policy.md
allow-licenses:
- 'Apache-2.0'
- 'BSD-2-Clause'
- 'BSD-2-Clause-FreeBSD'
- 'BSD-3-Clause'
- 'ISC'
- 'MIT'
- 'PostgreSQL'
- 'Python-2.0'
- 'Ruby'
- 'X11'
- 'Zlib'

allow-dependencies-licenses:
# The following packages are available under multiple licenses, or aren't detected by the dependency review action
# https://github.com/actions/dependency-review-action/issues/263
# 'Apache-2.0'
- pkg:gem/addressable
- pkg:gem/aws-eventstream
- pkg:gem/aws-partitions
- pkg:gem/aws-sdk-cloudwatchlogs
- pkg:gem/aws-sdk-core
- pkg:gem/aws-sdk-kms
- pkg:gem/aws-sdk-s3
- pkg:gem/aws-sdk-sqs
- pkg:gem/aws-sigv4
- pkg:gem/elasticsearch
- pkg:gem/elasticsearch-api
- pkg:gem/elasticsearch-transport
- pkg:gem/ffi-compiler
- pkg:gem/fluent-config-regexp-type
- pkg:gem/fluent-mixin-config-placeholders
- pkg:gem/fluent-plugin-datadog
- pkg:gem/fluent-plugin-elasticsearch
- pkg:gem/fluent-plugin-kubernetes_metadata_filter
- pkg:gem/fluent-plugin-multi-format-parser
- pkg:gem/fluent-plugin-prometheus
- pkg:gem/fluent-plugin-rabbitmq
- pkg:gem/fluent-plugin-rewrite-tag-filter
- pkg:gem/fluent-plugin-route
- pkg:gem/fluent-plugin-s3
- pkg:gem/fluent-plugin-splunk-enterprise
- pkg:gem/fluent-plugin-sumologic_output
- pkg:gem/fluentd
- pkg:gem/jmespath
- pkg:gem/msgpack
- pkg:gem/prometheus-client
- pkg:gem/serverengine
- pkg:gem/uuidtools
# 'BSD-2-Clause'
- pkg:gem/benchmark
- pkg:gem/cgi
- pkg:gem/csv
- pkg:gem/date
- pkg:gem/dbm
- pkg:gem/delegate
- pkg:gem/domain_name
- pkg:gem/etc
- pkg:gem/ext_monitor
- pkg:gem/fcntl
- pkg:gem/fileutils
- pkg:gem/forwardable
- pkg:gem/getoptlong
- pkg:gem/ipaddr
- pkg:gem/irb
- pkg:gem/logger
- pkg:gem/matrix
- pkg:gem/mutex_m
- pkg:gem/net-pop
- pkg:gem/net-smtp
- pkg:gem/observer
- pkg:gem/open3
- pkg:gem/ostruct
- pkg:gem/prime
- pkg:gem/pstore
- pkg:gem/readline-ext
- pkg:gem/rexml
- pkg:gem/rss
- pkg:gem/ruby2_keywords
- pkg:gem/singleton
- pkg:gem/stringio
- pkg:gem/strptime
- pkg:gem/strscan
- pkg:gem/timeout
- pkg:gem/tracer
- pkg:gem/unf
- pkg:gem/uri
- pkg:gem/webrick
- pkg:gem/yaml
- pkg:gem/zlib
# 'BSD-3-Clause'
- pkg:gem/ffi
# 'MIT'
- pkg:gem/amq-protocol
- pkg:gem/async
- pkg:gem/async-http
- pkg:gem/async-io
- pkg:gem/async-pool
- pkg:gem/bundler
- pkg:gem/bunny
- pkg:gem/concurrent-ruby
- pkg:gem/connection_pool
- pkg:gem/console
- pkg:gem/cool.io
- pkg:gem/did_you_mean
- pkg:gem/excon
- pkg:gem/faraday
- pkg:gem/faraday-em_http
- pkg:gem/faraday-em_synchrony
- pkg:gem/faraday-excon
- pkg:gem/faraday-httpclient
- pkg:gem/faraday-multipart
- pkg:gem/faraday-net_http
- pkg:gem/faraday-net_http_persistent
- pkg:gem/faraday-patron
- pkg:gem/faraday-rack
- pkg:gem/faraday-retry
- pkg:gem/fiber-local
- pkg:gem/fluent-plugin-cloudwatch-logs
- pkg:gem/fluent-plugin-record-modifier
- pkg:gem/fluent-plugin-remote-syslog
- pkg:gem/http
- pkg:gem/http_parser.rb
- pkg:gem/http-accept
- pkg:gem/http-cookie
- pkg:gem/http-form_data
- pkg:gem/http-parser
- pkg:gem/jsonpath
- pkg:gem/kubeclient
- pkg:gem/lru_redux
- pkg:gem/mime-types
- pkg:gem/mime-types-data
- pkg:gem/multi_json
- pkg:gem/multipart-post
- pkg:gem/net-http-persistent
- pkg:gem/netrc
- pkg:gem/nio4r
- pkg:gem/oj
- pkg:gem/protocol-hpack
- pkg:gem/protocol-http
- pkg:gem/protocol-http1
- pkg:gem/protocol-http2
- pkg:gem/psych
- pkg:gem/public_suffix
- pkg:gem/racc
- pkg:gem/rake
- pkg:gem/recursive-open-struct
- pkg:gem/rest-client
- pkg:gem/sigdump
- pkg:gem/syslog_protocol
- pkg:gem/timers
- pkg:gem/tzinfo
- pkg:gem/tzinfo-data
- pkg:gem/unf_ext
- pkg:gem/yajl-ruby
# 'Ruby'
- pkg:gem/bigdecimal
- pkg:gem/httpclient
- pkg:gem/json
- pkg:gem/openssl
- pkg:gem/readline
- pkg:gem/reline
