# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem "fluent-plugin-cloudwatch-logs", "0.14.3"
gem "fluent-plugin-datadog", "0.14.4"
gem "fluent-plugin-kubernetes_metadata_filter", "3.6.0"
gem "fluent-plugin-multi-format-parser", "1.1.0"
gem "fluent-plugin-newrelic", "1.2.3"
gem "fluent-plugin-prometheus", "2.2.0"
gem "fluent-plugin-rabbitmq", "0.1.3"
gem "fluent-plugin-record-modifier", "2.2.0"
gem "fluent-plugin-remote-syslog", "1.1"
gem "fluent-plugin-rewrite-tag-filter", "2.4.0"
gem "fluent-plugin-route", "1.0.0"
gem "fluent-plugin-s3", "1.8.2"
gem "fluent-plugin-splunk-enterprise", "0.10.2"
gem "fluent-plugin-sumologic_output", "1.10.0"
gem "fluentd", "1.17.1"
