# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem "fluent-plugin-cloudwatch-logs"
gem "fluent-plugin-datadog"
gem "fluent-plugin-kubernetes_metadata_filter"
gem "fluent-plugin-multi-format-parser"
gem "fluent-plugin-prometheus"
gem "fluent-plugin-rabbitmq"
gem "fluent-plugin-record-modifier"
gem "fluent-plugin-remote-syslog"
gem "fluent-plugin-rewrite-tag-filter"
gem "fluent-plugin-route"
gem "fluent-plugin-s3"
gem "fluent-plugin-splunk-enterprise"
gem "fluent-plugin-sumologic_output"
