name: Publish insights-scanner image

on:
  push:
    branches:
      - 'main'
      - 'build-image'
    paths:
      - 'insights-scanner/**'
      - '.github/workflows/insights-scanner-image.yaml'
    tags:
      - 'insights-scanner-v*.*.*'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'insights-scanner/**'
      - '.github/workflows/insights-scanner-image.yaml'

jobs:
  docker:
    permissions:
      attestations: write
      contents: read
      id-token: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout PR
        uses: actions/checkout@v4
        if: ${{ github.event_name == 'pull_request' }}
        with:
          fetch-depth: "0"
          ref: ${{ github.event.pull_request.head.sha }}
      -
        name: Checkout Branch or Tag
        uses: actions/checkout@v4
        if: ${{ github.event_name != 'pull_request' }}
        with:
          fetch-depth: "0"
      -
        name: Create SERVICE_TAG variable
        id: service_tag_var
        run: |
          RAW_TAG=$(echo $(git describe --abbrev=0 --tags --match 'insights-scanner-*'))
          SERVICE_TAG=${RAW_TAG#"insights-scanner-"}
          echo "using insights-scanner tag $SERVICE_TAG"
          echo "SERVICE_TAG=$SERVICE_TAG" >> $GITHUB_ENV
      -
        name: Set version for non-tag build
        if: "!startsWith(github.ref, 'refs/tags/insights-scanner')"
        id: version_non-tag_build
        run: |
          DOCKER_TAG=${{ env.SERVICE_TAG }}-$(git rev-parse --short=8 HEAD)
          echo "DOCKER_TAG=$DOCKER_TAG" >> $GITHUB_ENV
          echo "insights-scanner version $DOCKER_TAG"
      -
        name: Set version for tag build
        if: "startsWith(github.ref, 'refs/tags/insights-scanner')"
        id: version_tag_build
        run: |
          DOCKER_TAG=${{ env.SERVICE_TAG }}
          echo "DOCKER_TAG=$DOCKER_TAG" >> $GITHUB_ENV
          echo "insights-scanner version $DOCKER_TAG"
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ github.repository_owner }}/insights-scanner
            ghcr.io/${{ github.repository_owner }}/insights-scanner
          tags: |
            # set edge tag for default branch
            type=edge,enable={{is_default_branch}}
            # set tag+build for default branch
            type=raw,value=${{ env.DOCKER_TAG}},enable={{is_default_branch}}
            # tag event
            type=raw,value=${{ env.DOCKER_TAG}},enable=${{ startsWith(github.ref, 'refs/tags/insights-scanner') }}
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/insights-scanner') }}
            # pull request event
            type=ref,event=pr
            # pull request event
            type=ref,event=branch
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        id: build-and-push
        with:
          context: insights-scanner
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Attest dockerhub image
        uses: actions/attest-build-provenance@1c608d11d69870c2092266b3f9a6f3abbf17002c # v1.4.3
        with:
          subject-digest: ${{steps.build-and-push.outputs.digest}}
          subject-name: index.docker.io/${{ github.repository_owner }}/insights-scanner
          push-to-registry: true
      - name: Attest ghcr image
        uses: actions/attest-build-provenance@1c608d11d69870c2092266b3f9a6f3abbf17002c # v1.4.3
        with:
          subject-digest: ${{steps.build-and-push.outputs.digest}}
          subject-name: ghcr.io/${{ github.repository_owner }}/insights-scanner
          push-to-registry: true
