name: Publish logs-concentrator image

on:
  push:
    branches:
      - 'main'
      - 'build-image'
    paths:
      - 'logs-concentrator/**'
      - '.github/workflows/logs-concentrator-image.yaml'
    tags:
      - 'logs-concentrator-v*.*.*'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'logs-concentrator/**'
      - '.github/workflows/logs-concentrator-image.yaml'

jobs:
  docker:
    permissions:
      attestations: write
      contents: write
      id-token: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout PR
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        if: ${{ github.event_name == 'pull_request' }}
        with:
          fetch-depth: "0"
          ref: ${{ github.event.pull_request.head.sha }}
      -
        name: Checkout Branch or Tag
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        if: ${{ github.event_name != 'pull_request' }}
        with:
          fetch-depth: "0"
      -
        name: Create SERVICE_TAG variable
        id: service_tag_var
        run: |
          RAW_TAG=$(git describe --abbrev=0 --tags --match 'logs-concentrator-*')
          SERVICE_TAG=${RAW_TAG#"logs-concentrator-"}
          echo "using logs-concentrator tag $SERVICE_TAG"
          echo "SERVICE_TAG=$SERVICE_TAG" >> "$GITHUB_ENV"
      -
        name: Set version for non-tag build
        if: "!startsWith(github.ref, 'refs/tags/logs-concentrator')"
        id: version_non-tag_build
        run: |
          DOCKER_TAG="${{ env.SERVICE_TAG }}-$(git rev-parse --short=8 HEAD)"
          echo "DOCKER_TAG=$DOCKER_TAG" >> "$GITHUB_ENV"
          echo "logs-concentrator version $DOCKER_TAG"
      -
        name: Set version for tag build
        if: "startsWith(github.ref, 'refs/tags/logs-concentrator')"
        id: version_tag_build
        run: |
          DOCKER_TAG=${{ env.SERVICE_TAG }}
          echo "DOCKER_TAG=$DOCKER_TAG" >> "$GITHUB_ENV"
          echo "logs-concentrator version $DOCKER_TAG"
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5.7.0
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ github.repository_owner }}/logs-concentrator
            ghcr.io/${{ github.repository_owner }}/logs-concentrator
          tags: |
            # set edge tag for default branch
            type=edge,enable={{is_default_branch}}
            # set tag+build for default branch
            type=raw,value=${{ env.DOCKER_TAG}},enable={{is_default_branch}}
            # tag event
            type=raw,value=${{ env.DOCKER_TAG}},enable=${{ startsWith(github.ref, 'refs/tags/logs-concentrator') }}
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/logs-concentrator') }}
            # pull request event
            type=ref,event=pr
            # pull request event
            type=ref,event=branch
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
      -
        name: Login to DockerHub
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GHCR
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        id: build-and-push
        with:
          context: logs-concentrator
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Attest dockerhub image
        uses: actions/attest-build-provenance@e8998f949152b193b063cb0ec769d69d929409be # v2.4.0
        with:
          subject-digest: ${{steps.build-and-push.outputs.digest}}
          subject-name: index.docker.io/${{ github.repository_owner }}/logs-concentrator
          push-to-registry: true
      - name: Attest ghcr image
        uses: actions/attest-build-provenance@e8998f949152b193b063cb0ec769d69d929409be # v2.4.0
        with:
          subject-digest: ${{steps.build-and-push.outputs.digest}}
          subject-name: ghcr.io/${{ github.repository_owner }}/logs-concentrator
          push-to-registry: true
      - uses: anchore/sbom-action@9246b90769f852b3a8921f330c59e0b3f439d6e9 # v0.20.1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          image: ghcr.io/${{ github.repository_owner }}/logs-concentrator@${{steps.build-and-push.outputs.digest}}
          output-file: sbom.spdx.json
          upload-artifact: false
          upload-release-assets: false
      - name: Release
        uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8 # v2.3.2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            sbom.spdx.json
